# This is used to auth HCE against AWS
apiVersion: v1
kind: Secret
metadata:
  name: cloud-secret
type: Opaque
stringData:
  cloud_config.yml: |-
    # Add the cloud AWS credentials respectively
    [default]
    aws_access_key_id = SED_ACCESS_KEY_ID
    aws_secret_access_key = SED_SECRET_ACCESS_KEY