apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
spec:
  type: NodePort
  selector:
    app: guestbook-ui
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080  # Optional: must be in range 30000–32767
