apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: react-app-idp-stage
  title: Create React App (IDP Stage - Shared Token)
  description: A template to create a new react app with shared token.
  tags:
    - nextjs
    - react
    - javascript
spec:
  owner: engineering
  type: service
  parameters:
    - title: Next.js app details
      required:
        - service_name
      properties:
        service_name:
          title: Name of your new service
          type: string
          description: Unique app name (no spaces)
    - title: Service Infrastructure Details
      required:
        - owner
      properties:
        owner:
          title: Choose an Owner for the Service
          type: string
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
        # This field is hidden but needed to authenticate the request to trigger the pipeline
        token:
          title: Harness Token
          type: string
          ui:field: HarnessAuthToken
  steps:
    - id: trigger
      name: Creating your react app
      action: trigger:harness-custom-pipeline
      input:
        url: "<pipeline URL here>"
        inputset:
          service_name: ${{ parameters.service_name }}
        apikey: ${{ parameters.token }}

  output:
    links:
      - title: Pipeline Details
        url: ${{ steps.trigger.output.PipelineUrl }}
